## Fancy Indexing

In [57]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
arr=a[[0,3,5,6,2]]
arr

array([1, 4, 6, 7, 3])

In [65]:
arr=a[[9,7,6,4,3,1]]
arr

array([10,  8,  7,  5,  4,  2])

In [75]:
a=np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [77]:
arr=a[[0,1,2,3],[3,1,3,3]]
arr

array([ 3,  5, 11, 15])

In [83]:
arr=a[[0,0,1,1,2,2,3,3],[0,0,1,1,2,2,3,3]]
arr

array([ 0,  0,  5,  5, 10, 10, 15, 15])

In [85]:
array=a[[1,0,2,3,2],[0,1,3,2,1]]
arr

array([ 0,  0,  5,  5, 10, 10, 15, 15])