## Numpy Start

### What is numpy?
NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

### Numpy Arrays Vs Python Sequences
.NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

.The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

.NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

.A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [10]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [12]:
import numpy as np
a=np.array([22,23,24,15])
print(a)

[22 23 24 15]


In [26]:
import numpy as np
a=np.array([[2,2,2],[4,1,3]])
print(a)

[[2 2 2]
 [4 1 3]]


In [30]:
import numpy as np
a=np.array([[[3,4,5],[6,7,8],[9,10,11]]])
print(a)

[[[ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]]


In [34]:
import numpy as np
a=np.array([[[[21,22,23,24],[25,26,27,28],[29,30,31,32],[33,34,35,36]]]])
print(a)

[[[[21 22 23 24]
   [25 26 27 28]
   [29 30 31 32]
   [33 34 35 36]]]]


In [36]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [38]:
np.array([1,2,3],dtype=int)

array([1, 2, 3])

In [42]:
np.array([1,2,3],dtype=bool)

array([ True,  True,  True])

In [44]:
np.arange(2,50,5)

array([ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47])

In [46]:
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [52]:
np.arange(125).reshape(5,5,5)

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24]],

       [[ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49]],

       [[ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74]],

       [[ 75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94],
        [ 95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124]]])

In [60]:
np.ones((2,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [62]:
np.ones((((21,22,23,24))))

array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]],

        [[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]],

        [[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]],

        ...,

        [[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
    

In [90]:
np.ones((2.1,2.2,2.3,2.4 ), dtype=int

SyntaxError: incomplete input (2700234852.py, line 1)

In [96]:
shape = tuple(int(round(x)) for x in (2.1, 2.2, 2.3, 2.4))
np.ones(shape, dtype=int)


array([[[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]]])

In [98]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [100]:
np.random.random((5,6))

array([[0.98334166, 0.32631863, 0.34694719, 0.57125148, 0.51487546,
        0.68510725],
       [0.74895979, 0.43695927, 0.26655588, 0.99467556, 0.24356518,
        0.7682844 ],
       [0.66524369, 0.77077128, 0.61959002, 0.66191655, 0.88281592,
        0.53044308],
       [0.06129107, 0.21072812, 0.69440545, 0.12231541, 0.1248443 ,
        0.72516346],
       [0.79244369, 0.88363981, 0.67907174, 0.38360424, 0.51242833,
        0.11438707]])

In [102]:
np.linspace(-25,25,45,dtype=float)

array([-2.50000000e+01, -2.38636364e+01, -2.27272727e+01, -2.15909091e+01,
       -2.04545455e+01, -1.93181818e+01, -1.81818182e+01, -1.70454545e+01,
       -1.59090909e+01, -1.47727273e+01, -1.36363636e+01, -1.25000000e+01,
       -1.13636364e+01, -1.02272727e+01, -9.09090909e+00, -7.95454545e+00,
       -6.81818182e+00, -5.68181818e+00, -4.54545455e+00, -3.40909091e+00,
       -2.27272727e+00, -1.13636364e+00,  3.55271368e-15,  1.13636364e+00,
        2.27272727e+00,  3.40909091e+00,  4.54545455e+00,  5.68181818e+00,
        6.81818182e+00,  7.95454545e+00,  9.09090909e+00,  1.02272727e+01,
        1.13636364e+01,  1.25000000e+01,  1.36363636e+01,  1.47727273e+01,
        1.59090909e+01,  1.70454545e+01,  1.81818182e+01,  1.93181818e+01,
        2.04545455e+01,  2.15909091e+01,  2.27272727e+01,  2.38636364e+01,
        2.50000000e+01])

In [104]:
np.linspace(-10,10,45,dtype=int)

array([-10, -10, -10,  -9,  -9,  -8,  -8,  -7,  -7,  -6,  -6,  -5,  -5,
        -5,  -4,  -4,  -3,  -3,  -2,  -2,  -1,  -1,   0,   0,   0,   1,
         1,   2,   2,   3,   3,   4,   4,   5,   5,   5,   6,   6,   7,
         7,   8,   8,   9,   9,  10])

In [106]:
a=np.identity(5)
print(a)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## Array Attributes

In [109]:
a2 = np.arange(12,dtype=float).reshape(3,4)
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [113]:
a1 = np.arange(11,dtype=np.int64)
a1


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64)

In [115]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [123]:
print(a2.shape)
a2

(3, 4)


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [125]:
print(a1.size)
a1

11


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64)