1. ## what is numpy?

 a powerful Python library primarily used for numerical and scientific computing.

2. ## how to install numpy?

 pip install numpy

3. ## how to import numpy?

import numpy as np

4. ## how to create 1d numpy array?

In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


5. ## how to create 2d array?

In [3]:
import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr)


[[1 2 3]
 [4 5 6]]


6. ## what is the shape of an array?

the number of elements in each dimension.
NumPy array using the [.shape]

In [4]:
import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr.shape)


(2, 3)


7. ## how to check the data type of numpy array?

NumPy array using the .dtype

In [5]:
import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4])

# Check the data type
print(arr.dtype)



int32


8. ## how to create an array of all zeroes?

by using np.zeros()

In [6]:
import numpy as np

arr_1d = np.zeros(5)  
print(arr_1d)


arr_2d = np.zeros((2, 3))  
print(arr_2d)


[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


9. ## how to create an array of all ones?

by using np.ones()

In [7]:
import numpy as np

arr_1d = np.ones(5)  
print(arr_1d)

arr_2d = np.ones((2, 3))  
print(arr_2d)


[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


10. ## how to create a range of numbers?

11. ## how to create random numbers?

by using np.random

In [12]:
import numpy as np

rand_num = np.random.random()
print(rand_num)

rand_arr = np.random.random(5)
printrrandom_arr)


SyntaxError: unmatched ')' (3984829554.py, line 7)