# Numpy Start

## What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

## Numpy Arrays Vs Python Sequences

.NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

.The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

.NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

.A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

## Creating Numpy Arrays

In [2]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
import numpy as np
a=np.array([22,23,24,15])
print(a)

[22 23 24 15]


In [4]:
import numpy as np
a=np.array([[2,2,2],[4,1,3]])
print(a)

[[2 2 2]
 [4 1 3]]


In [5]:
import numpy as np
a=np.array([[[3,4,5],[6,7,8],[9,10,11]]])
print(a)

[[[ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]]


In [6]:
import numpy as np
a=np.array([[[[21,22,23,24],[25,26,27,28],[29,30,31,32],[33,34,35,36]]]])
print(a)

[[[[21 22 23 24]
   [25 26 27 28]
   [29 30 31 32]
   [33 34 35 36]]]]


In [7]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [8]:
np.array([1,2,3],dtype=int)


array([1, 2, 3])

In [9]:
np.array([1,2,3],dtype=bool)

array([ True,  True,  True])

In [10]:
np.arange(2,50,5)

array([ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47])

In [11]:
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [12]:
np.arange(125).reshape(5,5,5)

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24]],

       [[ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49]],

       [[ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74]],

       [[ 75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94],
        [ 95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124]]])

In [13]:
np.ones((2,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [17]:
np.ones(((21,22,23)))

array([[[1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        ...,
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.]],

       [[1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        ...,
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.]],

       [[1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        ...,
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.]],

       ...,

       [[1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        ...,
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1.

In [18]:
np.ones((2.1,2.2,2.3,2.4 ), dtype=int

SyntaxError: incomplete input (2700234852.py, line 1)

In [19]:
shape = tuple(int(round(x)) for x in (2.1, 2.2, 2.3, 2.4))
np.ones(shape, dtype=int)

array([[[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]]])

In [20]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.random.random((5,6))

array([[0.92568948, 0.04124578, 0.45939846, 0.42230731, 0.85276336,
        0.97392252],
       [0.8375581 , 0.49088525, 0.49838204, 0.90883642, 0.43671585,
        0.06927783],
       [0.14718337, 0.40234372, 0.27533297, 0.31920775, 0.94540151,
        0.8418348 ],
       [0.27770812, 0.90238918, 0.83188844, 0.5857645 , 0.33610456,
        0.21249376],
       [0.81533529, 0.53989904, 0.09875262, 0.7241361 , 0.85238956,
        0.0770623 ]])

In [22]:
np.linspace(-25,25,45,dtype=float)

array([-2.50000000e+01, -2.38636364e+01, -2.27272727e+01, -2.15909091e+01,
       -2.04545455e+01, -1.93181818e+01, -1.81818182e+01, -1.70454545e+01,
       -1.59090909e+01, -1.47727273e+01, -1.36363636e+01, -1.25000000e+01,
       -1.13636364e+01, -1.02272727e+01, -9.09090909e+00, -7.95454545e+00,
       -6.81818182e+00, -5.68181818e+00, -4.54545455e+00, -3.40909091e+00,
       -2.27272727e+00, -1.13636364e+00,  3.55271368e-15,  1.13636364e+00,
        2.27272727e+00,  3.40909091e+00,  4.54545455e+00,  5.68181818e+00,
        6.81818182e+00,  7.95454545e+00,  9.09090909e+00,  1.02272727e+01,
        1.13636364e+01,  1.25000000e+01,  1.36363636e+01,  1.47727273e+01,
        1.59090909e+01,  1.70454545e+01,  1.81818182e+01,  1.93181818e+01,
        2.04545455e+01,  2.15909091e+01,  2.27272727e+01,  2.38636364e+01,
        2.50000000e+01])

In [23]:
np.linspace(-10,10,45,dtype=int)

array([-10, -10, -10,  -9,  -9,  -8,  -8,  -7,  -7,  -6,  -6,  -5,  -5,
        -5,  -4,  -4,  -3,  -3,  -2,  -2,  -1,  -1,   0,   0,   0,   1,
         1,   2,   2,   3,   3,   4,   4,   5,   5,   5,   6,   6,   7,
         7,   8,   8,   9,   9,  10])

In [24]:
a=np.identity(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## Array Attributes

In [25]:
a2 = np.arange(12,dtype=float).reshape(3,4)
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [26]:
a1 = np.arange(11,dtype=np.int64)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64)

In [27]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [28]:
print(a2.shape)
a2


(3, 4)


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [30]:
print(a2.shape)
a2

(3, 4)


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [31]:
print(a1.size)
a1

11


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64)

# Changing Datatype

In [35]:
# astype
a2
a2.astype(np.int32)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## Array Operations

In [36]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [37]:
# scalar operations

# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [38]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [40]:
# vector operations
# arithmetic
a1 ** a2

array([[          0,           1,       16384,    14348907],
       [          0, -1564725563,  1159987200,   442181591],
       [          0,  1914644777, -1304428544,  -122979837]])

## Array Functions

In [41]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[24., 20., 74.],
       [ 7., 31.,  8.],
       [37., 84., 65.]])

In [42]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.prod(a1,axis=0)

array([ 6216., 52080., 38480.])

In [43]:
# mean/median/std/var
np.var(a1,axis=1)

array([603.55555556, 122.88888889, 372.66666667])

In [44]:
# trigonomoetric functions
np.sin(a1)

array([[-0.90557836,  0.91294525, -0.98514626],
       [ 0.6569866 , -0.40403765,  0.98935825],
       [-0.64353813,  0.73319032,  0.82682868]])

In [45]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [46]:
# log and exponents
np.exp(a1)

array([[2.64891221e+10, 4.85165195e+08, 1.37338298e+32],
       [1.09663316e+03, 2.90488497e+13, 2.98095799e+03],
       [1.17191424e+16, 3.02507732e+36, 1.69488924e+28]])

In [47]:
# round/floor/ceil

np.ceil(np.random.random((2,3))*100)

array([[96.,  5., 39.],
       [40., 82., 73.]])

## Indexing and Slicing

In [49]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)

a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [50]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
a1[2:5:2]

array([2, 4])

In [53]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [54]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [55]:
a2[1,::3]

array([4, 7])

In [56]:
a2[0,:]

array([0, 1, 2, 3])

In [57]:
a2[:,3]

array([ 3,  7, 11])

In [58]:
a = np.arange(27).reshape(3,3,3)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [62]:
a2[::2,2,]

array([ 2, 10])

## Iterating

In [66]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [67]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [68]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [69]:
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [70]:
for i in np.nditer(a1):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [71]:
for i in np.nditer(a2):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11


## Reshaping

In [72]:
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [73]:
a3.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

## stacking

In [74]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [75]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [76]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## Splitting

In [8]:
import numpy as npy
 
arr1 = npy.array([[1, 3, 5, 7], [2, 4, 6, 8]])
 
arr2 = npy.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
 
print(arr1.shape)
print(arr2.shape)

(2, 4)
(2, 2, 2)
